name: merodocument
description: Mero Document
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  auto_route: ^9.1.0
  bloc: ^8.1.3
  build_runner: ^2.4.11
  custom_refresh_indicator: ^3.1.2
  dartz: ^0.10.1
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_displaymode: ^0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  injectable: ^2.4.2
  injectable_generator: ^2.6.1
  intl: ^0.19.0
  logger: ^2.4.0
  permission_handler: ^11.3.1
  rename: ^3.0.2
  reorderable_grid_view: ^2.2.8

dev_dependencies:
  auto_route_generator: ^9.0.0
  bloc_test: ^9.1.6
  flutter_gen_runner: ^5.6.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/json/
    - assets/rive/
    - assets/svgs/

  # fonts:
  #   - family: Nothing
  #     fonts:
  #       - asset: assets/fonts/nothing.ttf

flutter_gen:
  output: lib/gen/
  line_length: 50
  integrations:
    flutter_svg: true
    flare_flutter: true
  assets:
    enabled: true
    outputs:
      class_name: MyAssets
      package_parameter_enabled: false
      style: dot-delimiter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo_1024.png"
  min_sdk_android: 21
